from __future__ import annotations

import asyncio
import logging

import psycopg
from fastapi import APIRouter, Depends, HTTPException, Request, WebSocket, WebSocketDisconnect
from pydantic import BaseModel

from api.rest.dependencies import get_store
from cv_ranker.db import CVStore, Message
from cv_ranker.websocket_manager import WSConnectionManager
from redis_streams.producer.chat_message_producer import ChatMessageStreamProducer

logger = logging.getLogger(__name__)

router = APIRouter()


class MessageCreateV2(BaseModel):
    role: str
    content: str


def get_stream_producer(request: Request) -> ChatMessageStreamProducer:
    return request.app.state.chat_message_stream_producer


def get_ws_connection_manager_v2(request: Request) -> WSConnectionManager:
    return request.app.state.ws_connection_manager_v2


@router.post("/v2/conversations/{conversation_id}/messages", status_code=201)
async def create_message_v2(
    conversation_id: int,
    body: MessageCreateV2,
    store: CVStore = Depends(get_store),
    producer: ChatMessageStreamProducer = Depends(get_stream_producer),
    ws_connection_manager: WSConnectionManager = Depends(get_ws_connection_manager_v2),
) -> Message:
    """v2 counterpart to `api.rest.app.create_message`.

    Same read-your-write shape (persist, broadcast over the v2 WebSocket
    topic, then hand off for an AI reply), but hands the message off to the
    v2 Redis Stream (`redis_streams.producer.chat_message_producer`) instead
    of Kafka; the AI reply itself is generated by the LangChain-based
    `redis_streams.consumer.recruiter_agent.RecruiterAgent` and relayed back
    over `redis_pubsub.producer.redis_pubsub_producer.AI_MODEL_RESPONSE_CHANNEL_V2`.
    """
    try:
        message_id = await asyncio.to_thread(store.create_message, conversation_id, body.role, body.content)
    except psycopg.errors.ForeignKeyViolation as exc:
        raise HTTPException(status_code=404, detail="Conversation not found") from exc
    message = await asyncio.to_thread(store.get_message, message_id)
    payload = {
        "id": message.id,
        "conversation_id": message.conversation_id,
        "role": message.role,
        "content": message.content,
        "created_at": message.created_at.isoformat(),
    }
    await ws_connection_manager.broadcast(payload["conversation_id"], payload)
    await producer.publish_message(message)
    return message


@router.websocket("/ws/v2/conversations/{conversation_id}")
async def conversation_messages_ws_v2(websocket: WebSocket, conversation_id: int) -> None:
    manager: WSConnectionManager = websocket.app.state.ws_connection_manager_v2
    await manager.connect(conversation_id, websocket)
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        manager.disconnect(conversation_id, websocket)
